### ISSUE TITLE
Error "cannot unmarshal response"

### ISSUE THREAD

**Issue by rfenouil** [performancecopilot/grafana-pcp#97]
Edit: First thank you so much for the awesome work :)

**Data source:** (please fill in)
PCP Redis (installed from Cockpit on Ubuntu 20.04.3 LTS)

**Describe the bug**
I observe some communication problems between PCP and 'grafana-pcp' plugin.
I prevents the proper creation of queries, and global experience is unstable (some hosts show data, others not, buggy interface).
Most relevant message is 
```
cannot unmarshal response: json: cannot unmarshal object into Go value of type pmseries.MetricNamesResponse
```

**To Reproduce**
1. Run
```
docker run \
            -e GF_INSTALL_PLUGINS="https://github.com/performancecopilot/grafana-pcp/releases/download/v3.2.0/performancecopilot-pcp-app-3.2.0.zip;performancecopilot-pcp-app" \
            -p 3001:3000 \
            grafana/grafana
```

2. Connect, enable plugin, add data source (in my case https://10.72.42.12:44322), import dashboard 'Host overview', save.
3. Create dashboard (or explore).
4. Select created source and start writing a query 'cpu'

**Expected behavior**
Autocompletion should help with the query.

**Observed behaviour**
A popup shows with error message 
```
Error
cannot unmarshal response: json: cannot unmarshal object into Go value of type pmseries.MetricNamesResponse
```

I also cannot access PCP menu (http://127.0.0.1:3001/a/performancecopilot-pcp-app) as it crashed with error message:
```
An unexpected error happened
DetailsTypeError: e.spacing is not a function

    at t (http://127.0.0.1:3001/public/plugins/performancecopilot-pcp-app/module.js:2:101225)
    at v (http://127.0.0.1:3001/public/build/5105.1322a38d8e955d3d27e7.js:2:971571)
    at WithTheme(undefined)
    at div
    at t (http://127.0.0.1:3001/public/plugins/performancecopilot-pcp-app/module.js:2:106802)
    at v (http://127.0.0.1:3001/public/build/5105.1322a38d8e955d3d27e7.js:2:971571)
    at div
    at div
    at div
    at t (http://127.0.0.1:3001/public/plugins/performancecopilot-pcp-app/module.js:2:57925)
    at WithTheme(undefined)
    at t (http://127.0.0.1:3001/public/plugins/performancecopilot-pcp-app/module.js:2:54603)
    at l (http://127.0.0.1:3001/public/build/5105.1322a38d8e955d3d27e7.js:2:969089)
    at t (http://127.0.0.1:3001/public/plugins/performancecopilot-pcp-app/module.js:2:124222)
    at e (http://127.0.0.1:3001/public/build/AppRootPage.1322a38d8e955d3d27e7.js:1:1873)
    at I (http://127.0.0.1:3001/public/build/AppRootPage.1322a38d8e955d3d27e7.js:1:4968)
    at n (http://127.0.0.1:3001/public/build/5105.1322a38d8e955d3d27e7.js:2:942013)
    at zi (http://127.0.0.1:3001/public/build/7095.1322a38d8e955d3d27e7.js:6394:193)
    at t (http://127.0.0.1:3001/public/build/5105.1322a38d8e955d3d27e7.js:2:989569)
    at t (http://127.0.0.1:3001/public/build/5105.1322a38d8e955d3d27e7.js:2:991590)
    at main
    at t (http://127.0.0.1:3001/public/build/5105.1322a38d8e955d3d27e7.js:2:986187)
    at div
    at Ws (http://127.0.0.1:3001/public/build/7095.1322a38d8e955d3d27e7.js:2158:1022)
    at d (http://127.0.0.1:3001/public/build/7095.1322a38d8e955d3d27e7.js:4481:26210)
    at Sl (http://127.0.0.1:3001/public/build/7095.1322a38d8e955d3d27e7.js:2870:458)
    at Tl (http://127.0.0.1:3001/public/build/7095.1322a38d8e955d3d27e7.js:2870:1006)
    at l (http://127.0.0.1:3001/public/build/5105.1322a38d8e955d3d27e7.js:2:969089)
    at Oo (http://127.0.0.1:3001/public/build/7095.1322a38d8e955d3d27e7.js:6474:384)
```

**Versions (please complete the following information):**
 - Performance Co-Pilot: pcp version 5.0.3
 - Grafana: Grafana v8.3.5 (a53fcac7b1)
 - grafana-pcp: 3.2.0
 - Redis (if applicable): Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=636cde3b5c7a3923

**Additional context**
cockpit 261-1~bpo20.04.1
cockpit-bridge 261-1~bpo20.04.1
cockpit-networkmanager 261-1~bpo20.04.1
cockpit-packagekit 261-1~bpo20.04.1
cockpit-pcp 215-1
cockpit-storaged 261-1~bpo20.04.1
cockpit-system 261-1~bpo20.04.1
cockpit-ws 261-1~bpo20.04.1

**Comment by rfenouil** [comment]
After more tests, with grafana-pcp version 3.2.1 (and grafana 8.3.6), the 'Metrics search' panel shows up, but any search returns:
```
Error: Network Error: Failed to fetch
```

**Comment by rfenouil** [comment]
And a modified curl query returns:

```
~$ curl "http://10.72.42.12:44322/series/metrics"
["mem.util.mapped","vfs.files.max","mem.numa.util.bounce","mem.vmstat.pgscan_direct","pmcd.version","network.ip.outbcastoctets","network.tcp.dsackofosent","kernel.all.pressure.memory.some.total","mem.vmstat.nr_active_anon","network.udp.incsumerrors","mem.freemem","mem.numa.util.active_anon","mem.util.committed_AS","network.tcp.lockdroppedicmps","mem.numa.util.used","disk.partitions.write_merge","kernel.all.cpu.intr","network.sockstat.tcp.inuse","network.softnet.cpu_collision","network.icmp.inaddrmasks","mem.vmstat.pgfree","kernel.all.pressure.io.full.avg","mem.numa.util.slabUnreclaimable","mem.vmstat.pgfault","kvm.halt_wakeup","network.tcp.spuriousrtos","network.ip6.intoobigerrors","disk.all.blkread","disk.dev.avactive","kvm.halt_exits","mem.vmstat.compact_fail","network.icmp.inparmprobs","kvm.insn_emulation_fail","network.icmp6.outrouteradvertisements","swap.free","hinv.pagesize","network.icmp6.inerrors","mem.util.active_anon","ipc.shm.used_ids","network.tcp.spuriousrtxhostqueues","pmcd.pmie.logfile","kernel.all.uptime","mem.vmstat.kswapd_inodesteal","mem.vmstat.pgsteal_kswapd","mem.zoneinfo.numa_foreign","mem.util.commitLimit","network.tcp.origdatasent","mem.zoneinfo.numa_hit","kernel.all.running","mem.vmstat.slabs_scanned","disk.all.write","disk.dev.scheduler","mem.vmstat.pgactivate","network.softnet.flow_limit_count","mem.zoneinfo.nr_anon_pages","mem.vmstat.unevictable_pgs_stranded","mem.numa.util.hugepagesFreeBytes","network.icmp6.outechoreplies","mem.vmstat.pgalloc_movable","network.icmp.outdestunreachs","network.icmp6.outpkttoobigs","kvm.halt_attempted_poll","network.tcp.attemptfails","network.tcp.fastopenpassive","mem.numa.util.kernelStack","network.sockstat.tcp.mem","disk.dev.write_bytes","network.interface.collisions","network.ip6.fragoks","mem.vmstat.nr_mlock","xfs.buffer.busy_locked","network.icmp.outaddrmaskreps","mem.vmstat.pgalloc_normal","disk.partitions.avactive","network.sockstat.tcp.orphan","kernel.percpu.cpu.vuser","mem.zoneinfo.workingset_refault","mem.vmstat.nr_inactive_anon","mem.vmstat.pgsteal_direct","ipc.msg.num_smsghdr","mem.zoneinfo.spanned","kvm.io_exits","kernel.uname.release","hinv.node.online","network.tcp.insegs","network.ip6.reasmreqds","pmcd.pmie.numrules","ipc.shm.max_seg","mem.util.kernelStack","network.icmp6.outechos","kvm.mmio_exits","network.tcp.fastopenpassivefail","kernel.percpu.cpu.irq.hard","disk.all.read_merge","hinv.cpu.flags","kvm.tlb_flush","network.icmp6.ingroupmembresponses","mem.zoneinfo.protection","network.tcp.fastopenactivefail","mem.numa.util.mlocked","network.icmp.outechoreps","network.icmp6.intimeexcds","xfs.buffer.get_locked_waited","kvm.irq_window","mem.numa.util.hugepagesSurpBytes","kernel.all.cpu.irq.soft","network.udp.indatagrams","kernel.percpu.cpu.vnice","network.softnet.percpu.cpu_collision","kernel.all.lastpid","disk.all.avactive","mem.util.directMap4k","mem.vmstat.thp_split_page","kvm.exits","disk.dev.read_merge","disk.partitions.total_bytes","ipc.msg.sz_pool","network.ip6.outnoroutes","hinv.ndisk","pmcd.pmie.eval.expected","mem.numa.util.anonpages","network.softnet.time_squeeze","mem.zoneinfo.free","mem.vmstat.pgdeactivate","network.udp6.indatagrams","mem.util.hugepagesSurp","mem.numa.alloc.foreign","kvm.mmu_cache_miss","network.icmp.outmsgs","network.icmp6.ingroupmembreductions","mem.numa.util.mapped","network.interface.out.errors","network.interface.wireless","ipc.sem.max_perid","mem.vmstat.nr_mapped","mem.vmstat.nr_dirty_background_threshold","network.tcp.rcvpruned","network.sockstat.raw6.inuse","network.ip.inoctets","network.icmp6.outtimeexcds","ipc.msg.tot_msg","pmcd.pmie.eval.false","network.tcp.timewaitkilled","mem.zoneinfo.workingset_activate","xfs.log.noiclogs","kernel.all.pressure.io.some.total","kernel.all.pressure.cpu.some.total","network.icmp.outredirects","pmcd.pmie.pmcd_host","mem.vmstat.pgmajfault","mem.util.hugepagesRsvdBytes","kernel.all.pressure.memory.full.avg","disk.partitions.read","mem.vmstat.pswpin","network.ip.fragcreates","disk.all.total_bytes","disk.dev.blkread","network.tcp.tsreorder","network.interface.mtu","network.tcp.fastretrans","network.tcp.md5unexpected","network.tcp.listendrops","network.ip6.inect0pkts","kernel.percpu.cpu.user","mem.util.mlocked","mem.util.anonhugepages","kvm.pf_fixed","mem.util.vmallocTotal","mem.util.directMap2M","ipc.sem.max_sem","network.udp6.noports","network.icmp6.outmldv2reports","network.udp6.rcvbuferrors","kernel.all.cpu.sys","mem.util.inactive_file","network.tcp.slowstartretrans","network.tcp.delayedacklocked","network.tcp.timewaitrecycled","ipc.msg.mapent","mem.zoneinfo.nr_written","network.tcp.renoreorder","network.ip.intruncatedpkts","mem.zoneinfo.nr_shmem","network.tcp.ofomerge","ipc.msg.max_msgseg","kernel.all.cpu.nice","ipc.sem.tot_sem","mem.ksm.pages_unshared","mem.ksm.run_state","network.ip6.inbcastoctets","mem.numa.util.writebackTmp","disk.partitions.read_rawactive","network.ip.inaddrerrors","network.ip.inunknownprotos","network.icmp6.inredirects","network.icmp6.inneighborsolicits","network.icmp.intimeexcds","network.ip.inmcastpkts","mem.numa.util.unevictable","network.ip6.inunknownprotos","network.udp.noports","disk.all.read_bytes","kvm.mmu_recycled","network.tcp.abortonclose","mem.numa.util.hugepagesSurp","network.ip.fragfails","network.tcp.rtoalgorithm","kvm.irq_injections","hinv.ninterface","network.interface.total.bytes","network.tcp.hpacks","network.ip.inbcastoctets","mem.util.directMap1G","disk.all.total_rawactive","mem.zoneinfo.nr_free_cma","network.ip6.inaddrerrors","mem.vmstat.compact_isolated","xfs.log.writes","mem.util.hugepagesRsvd","network.udp6.outdatagrams","kernel.all.entropy.avail","mem.util.other","mem.zoneinfo.managed","mem.numa.util.total","mem.zoneinfo.nr_alloc_batch","network.ip.defaultttl","network.udp6.incsumerrors","hinv.cpu.cache_alignment","network.ip.outrequests","network.interface.speed","network.tcp.renorecovery","mem.vmstat.compact_stall","mem.vmstat.thp_split_page_failed","filesys.capacity","network.tcp.sackrecovery","kvm.invlpg","mem.util.dirty","network.tcp.listenoverflows","network.ip6.fragcreates","network.sockstat.tcp6.inuse","mem.vmstat.nr_isolated_anon","network.icmp.outparmprobs","mem.util.available","network.icmp6.outparmproblems","mem.vmstat.numa_local","network.interface.out.bytes","network.interface.in.drops","pmcd.services","mem.vmstat.compact_free_scanned","mem.zoneinfo.nr_free_pages","network.ip.innoroutes","vfs.files.count","network.interface.out.compressed","mem.util.active_file","mem.numa.util.dirty","kernel.uname.distro","network.sockstat.total","network.icmp6.outredirects","kernel.uname.sysname","mem.zoneinfo.nr_active_file","network.icmp6.outneighborsolicits","mem.zoneinfo.nr_inactive_anon","kernel.all.hz","network.tcp.outrsts","mem.zoneinfo.numa_other","kernel.all.cpu.steal","mem.zoneinfo.nr_isolated_anon","network.tcp.abortontimeout","kernel.all.cpu.guest","mem.numa.util.inactive","mem.numa.util.inactive_file","kvm.mmu_pte_write","mem.util.hugepagesFree","network.ip6.indelivers","mem.zoneinfo.nr_isolated_file","kvm.mmu_pte_updated","network.ip.reasmfails","mem.numa.util.shmem","mem.vmstat.nr_zone_write_pending","mem.util.swapCached","network.tcp.sackfailures","network.icmp6.inparmproblems","network.tcp.abortondata","network.tcp.hphits","network.ip.inhdrerrors","network.icmp6.outgroupmembresponses","network.interface.baudrate","mem.numa.util.NFS_Unstable","mem.util.hugepagesTotal","network.icmp6.inechoreplies","kernel.all.idletime","network.ip6.innoectpkts","network.tcp.challengeack","network.icmp.insrcquenchs","mem.numa.alloc.hit","network.ip6.inhdrerrors","mem.vmstat.thp_collapse_alloc_failed","mem.vmstat.nr_dirty","disk.all.write_merge","kernel.all.cpu.idle","network.tcp.lostretransmit","mem.vmstat.pgrotated","disk.all.write_rawactive","mem.vmstat.unevictable_pgs_rescued","pmcd.pmlogger.host","kernel.percpu.cpu.nice","network.tcp.pawsactiverejected","kernel.all.load","mem.vmstat.pswpout","pmcd.pmie.eval.true","network.interface.in.compressed","network.ip.fragoks","mem.zoneinfo.nr_vmscan_write","network.tcp.incsumerrors","mem.zoneinfo.nr_mlock","network.udp.outdatagrams","network.interface.ipv6_addr","network.ip6.reasmfails","mem.vmstat.thp_zero_page_alloc","ipc.shm.tot","pmcd.pmlogger.port","network.icmp.inechoreps","network.sockstat.frag6.memory","disk.dev.total_rawactive","mem.numa.util.filePages","ipc.sem.max_semid","network.ip.inreceives","network.interface.in.packets","mem.vmstat.workingset_nodereclaim","kernel.all.pswitch","mem.vmstat.compact_daemon_wake","network.icmp6.inrouteradvertisements","network.tcp.sackdiscard","network.ip.forwarding","ipc.sem.max_ops","kernel.percpu.intr","mem.vmstat.numa_miss","xfs.log.blocks","network.icmp6.outgroupmembreductions","mem.ksm.pages_sharing","network.interface.running","disk.partitions.total_rawactive","network.tcp.dsackoldsent","network.sockstat.udplite6.inuse","mem.vmstat.kswapd_low_wmark_hit_quickly","network.ip.outmcastoctets","kernel.all.pressure.memory.full.total","network.tcp.prunecalled","mem.zoneinfo.nr_anon_transparent_hugepages","kernel.all.pressure.memory.some.avg","network.tcp.delayedacks","filesys.mountdir","hinv.physmem","network.icmp.outerrors","hinv.hugepagesize","mem.vmstat.nr_shmem_hugepages","mem.vmstat.balloon_inflate","disk.partitions.write","mem.vmstat.numa_hit","mem.vmstat.nr_free_pages","mem.vmstat.pglazyfreed","network.tcp.fastopenactive","hinv.map.cpu_num","mem.util.vmallocUsed","network.tcp.sackreneging","xfs.buffer.get_locked","xfs.buffer.page_retries","hinv.map.scsi","kernel.all.cpu.vuser","network.tcp.sackshifted","mem.ksm.pages_to_scan","network.tcp.autocorking","network.ip.inbcastpkts","pmcd.pmie.eval.unknown","mem.zoneinfo.high","network.tcp.dsackrecv","pmcd.numclients","network.ip6.incepkts","network.tcp.memorypressures","network.ip6.outdiscards","mem.vmstat.nr_dirty_threshold","network.ip6.inmcastpkts","mem.vmstat.pgalloc_dma32","network.interface.total.errors","network.tcp.delayedacklost","network.icmp6.outerrors","hinv.machine","ipc.shm.swp","network.icmp6.indestunreachs","vfs.dentry.free","swap.pagesout","network.tcp.dsackignoredold","filesys.blocksize","disk.dev.write_merge","mem.vmstat.nr_zone_inactive_anon","mem.zoneinfo.nr_unevictable","kernel.percpu.cpu.wait.total","xfs.write","hinv.cpu.online","mem.buddyinfo.pages","mem.util.active","network.tcp.ofoqueue","disk.all.read_rawactive","network.interface.in.bytes","mem.vmstat.thp_fault_alloc","mem.numa.alloc.other_node","disk.dev.read_bytes","network.icmp6.outgroupmembqueries","mem.vmstat.nr_zone_unevictable","network.icmp.outtimestampreps","network.ip.outnoroutes","mem.vmstat.numa_other","mem.vmstat.pgalloc_dma","mem.util.anonpages","network.ip.cepkts","network.ip.inmcastoctets","hinv.cpu.clock","swapdev.length","kvm.mmu_unsync","network.udp6.inerrors","disk.dev.total_bytes","mem.vmstat.thp_collapse_alloc","network.ip6.outrequests","mem.vmstat.nr_anon_pages","kvm.fpu_reload","mem.util.hugepagesTotalBytes","network.udp6.sndbuferrors","mem.vmstat.numa_pages_migrated","xfs.buffer.get_read","mem.vmstat.nr_slab_unreclaimable","kvm.irq_exits","network.icmp.indestunreachs","vfs.inodes.count","network.interface.total.packets","swap.used","mem.vmstat.nr_writeback","mem.vmstat.nr_shmem_pmdmapped","kernel.all.cpu.irq.hard","swap.out","ipc.shm.swap_attempts","hinv.cpu.bogomips","mem.util.swapTotal","kvm.remote_tlb_flush","mem.zoneinfo.nr_slab_reclaimable","network.icmp6.ingroupmembqueries","mem.util.slabUnreclaimable","ipc.shm.min_segsz","vfs.dentry.count","mem.zoneinfo.nr_slab_unreclaimable","network.interface.out.carrier","network.ip.forwdatagrams","disk.partitions.read_bytes","hinv.nfilesys","network.sockstat.tcp.alloc","swap.pagesin","network.ip.reasmoks","network.tcp.renofailures","pmcd.pmlogger.archive","network.icmp.outaddrmasks","disk.partitions.aveq","ipc.sem.max_undoent","mem.zoneinfo.numa_miss","ipc.msg.max_defmsgq","network.tcp.fastopencookiereqd","network.sockstat.udp.mem","mem.vmstat.nr_unstable","mem.vmstat.nr_written","kvm.hypercalls","mem.zoneinfo.nr_kernel_stack","mem.zoneinfo.nr_dirty","kvm.nmi_injections","mem.util.bufmem","network.ip6.indiscards","hinv.cpu.cache","disk.dev.write_rawactive","network.ip6.inmcastoctets","network.ip6.outmcastpkts","network.icmp.outsrcquenchs","mem.vmstat.nr_inactive_file","network.icmp.inredirects","network.icmp.outtimestamps","network.tcp.ofopruned","mem.vmstat.nr_unevictable","network.ip6.reasmtimeout","network.tcp.syncookiesfailed","network.interface.out.packets","network.ip6.inoctets","mem.numa.util.hugepagesFree","kernel.percpu.cpu.idle","kernel.uname.machine","pmcd.agent.status","disk.dev.blkwrite","swap.length","pmcd.pmie.configfile","network.interface.up","kernel.all.cpu.vnice","mem.zoneinfo.nr_writeback_temp","network.interface.duplex","ipc.shm.rss","disk.all.total","mem.zoneinfo.nr_active_anon","network.tcp.inerrs","network.tcp.outsegs","mem.vmstat.nr_dirtied","mem.numa.util.hugepagesTotalBytes","mem.zoneinfo.scanned","mem.vmstat.nr_zone_active_anon","mem.util.swapFree","mem.physmem","kernel.percpu.cpu.steal","network.tcp.rtomax","mem.zoneinfo.nr_mapped","kernel.all.sysfork","network.ip6.inreceives","network.ip6.reasmoks","mem.util.inactive_anon","network.icmp6.incsumerrors","mem.numa.util.slabReclaimable","disk.all.blkwrite","hinv.map.cpu_node","network.tcp.sackrecoveryfail","mem.zoneinfo.nr_unstable","mem.vmstat.nr_vmscan_write","mem.util.shmem","network.tcp.renorecoveryfail","mem.zoneinfo.present","network.udp6.ignoredmulti","network.tcp.lossundo","xfs.buffer.miss_locked","vfs.files.free","network.icmp.intimestampreps","mem.vmstat.nr_slab_reclaimable","mem.zoneinfo.nr_bounce","mem.vmstat.numa_pte_updates","network.icmp.inechos","kernel.uname.nodename","mem.vmstat.pginodesteal","network.icmp.intimestamps","mem.vmstat.thp_file_alloc","mem.ksm.sleep_time","network.interface.out.fifo","mem.zoneinfo.low","network.tcp.lossfailures","mem.vmstat.thp_split","network.interface.ipv6_scope","kvm.insn_emulation","disk.dev.aveq","network.softnet.percpu.time_squeeze","mem.vmstat.nr_vmscan_immediate_reclaim","mem.numa.util.slab","network.tcp.outofwindowicmps","hinv.cpu.model_name","mem.util.hugepagesFreeBytes","network.tcp.embryonicrsts","disk.dev.read","network.tcp.wantzerowindowadv","network.udp.inerrors","kernel.all.cpu.user","mem.util.used","network.softnet.percpu.dropped","network.tcp.fastopenlistenoverflow","network.tcp.activeopens","mem.zoneinfo.nr_vmscan_immediate_reclaim","network.ip.reasmtimeout","mem.vmstat.pgmigrate_fail","disk.dev.write","mem.vmstat.compact_migrate_scanned","mem.vmstat.nr_isolated_file","mem.util.vmallocChunk","mem.vmstat.nr_zone_active_file","network.interface.total.drops","network.ip.ect1pkts","ipc.shm.max_segsz","mem.vmstat.pgpgout","network.ip.noectpkts","disk.all.read","mem.vmstat.nr_writeback_temp","kvm.efer_reload","mem.vmstat.nr_free_cma","mem.vmstat.htlb_buddy_alloc_fail","ipc.msg.used_queues","network.tcp.sackmerged","mem.vmstat.nr_kernel_stack","xfs.quota.cachehits","mem.vmstat.balloon_deflate","network.interface.in.mcasts","mem.zoneinfo.nr_file_pages","disk.dev.total","mem.util.cache_clean","network.ip.outdiscards","ipc.sem.max_semmap","network.tcp.fromzerowindowadv","disk.partitions.total","network.tcp.rtomin","network.tcp.retranssegs","network.tcp.busypollrxpackets","filesys.full","mem.numa.util.hugepagesTotal","network.icmp.outtimeexcds","network.softnet.received_rps","network.tcp.synretrans","kvm.request_irq","mem.vmstat.balloon_migrate","kvm.mmu_flooded","mem.vmstat.unevictable_pgs_culled","network.tcp.arpfilter","network.ip6.outbcastoctets","kvm.largepages","mem.zoneinfo.numa_local","kernel.all.pressure.io.full.total","swap.in","mem.vmstat.nr_bounce","network.interface.in.frame","network.tcp.tozerowindowadv","network.tcp.sackshiftfallback","mem.zoneinfo.nr_dirtied","kvm.signal_exits","xfs.read","hinv.nnode","network.tcp.estabresets","mem.ksm.pages_volatile","mem.vmstat.thp_file_mapped","mem.vmstat.nr_shmem","ipc.msg.tot_bytes","network.sockstat.udplite.inuse","ipc.shm.max_shmsys","pmcd.pid","kernel.percpu.cpu.intr","mem.buddyinfo.total","network.ip6.intruncatedpkts","hinv.ntape","network.icmp6.inmsgs","kvm.pf_guest","disk.partitions.read_merge","mem.vmstat.thp_fault_fallback","network.tcp.minttldrop","disk.all.aveq","ipc.msg.max_msgsz","disk.dev.read_rawactive","mem.numa.util.active","swapdev.vlength","mem.util.writeback","disk.partitions.blkread","network.tcp.syncookiessent","mem.vmstat.htlb_buddy_alloc_success","kernel.all.runnable","mem.util.unevictable","mem.util.hugepagesSurpBytes","mem.vmstat.pageoutrun","vfs.inodes.free","network.tcp.rcvcoalesce","xfs.buffer.page_found","mem.numa.util.inactive_anon","network.ip.indelivers","network.tcp.maxconn","pmcd.seqnum","network.softnet.percpu.received_rps","network.tcp.retransfail","kernel.all.pressure.cpu.some.avg","network.tcp.pureacks","mem.vmstat.thp_zero_page_alloc_failed","network.icmp6.outdestunreachs","network.ip6.fragfails","mem.vmstat.nr_zspages","network.sockstat.frag.inuse","mem.vmstat.nr_slab","mem.util.cached","disk.all.blktotal","mem.vmstat.unevictable_pgs_mlocked","kernel.percpu.cpu.sys","network.ip6.inect1pkts","network.tcp.md5notfound","network.udp.recvbuferrors","network.ip.outoctets","network.ip.outmcastpkts","swapdev.priority","mem.numa.util.writeback","network.sockstat.udp6.inuse","pmcd.build","xfs.write_bytes","mem.util.free","pmcd.pmie.eval.actual","network.tcp.iprpfilter","kernel.all.cpu.guest_nice","network.tcp.abortonmemory","network.interface.out.drops","network.icmp6.inmldv2reports","ipc.sem.max_semval","mem.vmstat.unevictable_pgs_scanned","network.interface.hw_addr","mem.zoneinfo.numa_interleave","network.tcp.synchallenge","network.interface.total.mcasts","disk.partitions.write_bytes","mem.vmstat.pgscan_kswapd","ipc.sem.used_sem","mem.vmstat.nr_page_table_pages","pmcd.pmie.actions","kernel.all.cpu.wait.total","kvm.mmu_shadow_zapped","kernel.percpu.cpu.guest","mem.vmstat.compact_success","mem.zoneinfo.min","mem.zoneinfo.nr_writeback","network.icmp.inmsgs","mem.vmstat.nr_active_file","mem.numa.alloc.miss","mem.zoneinfo.nr_inactive_file","network.icmp6.outmsgs","network.tcp.abortfailed","xfs.buffer.create","mem.numa.alloc.interleave_hit","network.ip.csumerrors","kernel.percpu.cpu.irq.soft","hinv.ncpu","kvm.nmi_window","network.ip.reasmreqds","hinv.cpu.stepping","xfs.buffer.get","kernel.uname.version","network.icmp6.inneighboradvertisements","mem.ksm.pages_shared","network.icmp.inaddrmaskreps","network.sockstat.raw.inuse","kernel.percpu.cpu.guest_nice","mem.vmstat.pgpgin","mem.vmstat.nr_anon_transparent_hugepages","network.icmp.inerrors","network.tcp.ofodrop","network.tcp.reqqfulldocookies","network.icmp6.inroutersolicits","network.tcp.dsackignorednoundo","mem.util.pageTables","network.tcp.abortonlinger","network.tcp.passiveopens","network.ip.ect0pkts","network.tcp.lossprobes","disk.partitions.blktotal","kernel.all.blocked","network.interface.in.fifo","network.tcp.lossproberecovery","network.icmp6.inpkttoobigs","network.tcp.dsackundo","network.tcp.sackreorder","mem.util.inactive","network.tcp.reqqfulldrop","network.ip6.outoctets","kernel.all.nusers","kernel.all.interrupts.errors","network.udp.sndbuferrors","network.tcp.dsackoforecv","network.tcp.timeouts","mem.vmstat.pgscan_direct_throttle","network.icmp6.outneighboradvertisements","mem.vmstat.numa_foreign","mem.vmstat.unevictable_pgs_munlocked","mem.numa.util.active_file","mem.vmstat.kswapd_high_wmark_hit_quickly","mem.ksm.merge_across_nodes","ipc.sem.num_undo","mem.util.NFS_Unstable","ipc.sem.max_exit","network.ip.indiscards","xfs.read_bytes","mem.vmstat.thp_split_pmd","network.icmp.incsumerrors","network.icmp.outechos","network.sockstat.udp.inuse","network.tcp.currestab","mem.vmstat.pgmigrate_success","network.icmp6.outroutersolicits","pmda.uname","mem.util.bounce","ipc.shm.swap_successes","hinv.cpu.model","mem.vmstat.drop_pagecache","network.sockstat.frag.memory","network.tcp.timewaited","mem.numa.util.free","mem.vmstat.drop_slab","pmcd.numagents","network.softnet.dropped","network.tcp.pawsestabrejected","kernel.all.intr","kernel.all.entropy.poolsize","ipc.msg.max_seg","network.ip6.innoroutes","disk.partitions.blkwrite","network.ip6.outmcastoctets","mem.vmstat.thp_deferred_split_page","swapdev.free","mem.vmstat.nr_zone_inactive_file","mem.util.slab","mem.zoneinfo.nr_page_table_pages","network.softnet.percpu.flow_limit_count","kvm.mmu_pde_zapped","disk.partitions.write_rawactive","kvm.host_state_reload","mem.numa.alloc.local_node","mem.vmstat.numa_interleave","network.sockstat.tcp.tw","network.icmp6.inechos","network.ip6.outforwdatagrams","kernel.all.pressure.io.some.avg","mem.vmstat.unevictable_pgs_cleared","ipc.sem.sz_semundo","swapdev.maxswap","network.sockstat.frag6.inuse","network.interface.inet_addr","mem.util.corrupthardware","network.interface.in.errors","kernel.all.pid_max","network.tcp.fullundo","network.tcp.syncookiesrecv","disk.all.write_bytes","network.tcp.backlogdrop","pmcd.pmlogger.pmcd_host","network.tcp.timewaitoverflow","ipc.msg.max_msgqid","hinv.cpu.vendor","network.tcp.partialundo","network.tcp.rcvcollapsed","mem.vmstat.zone_reclaim_failed","mem.zoneinfo.workingset_nodereclaim","kvm.halt_successful_poll","mem.util.slabReclaimable","network.ip.outbcastpkts","network.tcp.deferacceptdrop","mem.numa.util.pageTables","mem.ksm.full_scans"]
```

**Comment by rfenouil** [comment]
Sorry for the spam but I got it working by updating PCP and Redis to latest possible version on my servers.
On ubuntu, for PCP I installed 'pcp-zeroconf' and for Redis I added the 'ppa:redislabs/redis' so my sources list.
I now have:
 - pcp version 5.3.6
 - Redis server v=6.2.6 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=9c9e426e2f96cc51

And 'grafana-pcp' plugin seems happy. Autocompletion works in queries, data shows up in dashboards, and metrics search does not return an error anymore (though I don't know how to add redisearch to grafana container yet).

Does that look correct ? Any advice on ways to install/maintain compatible versions ?
Do you know of a public docker image with PCP/Redis ?

Thank you again for the great work.
